import os, sys

if 'BOOST_DIR' not in os.environ:
	sys.stderr.write('FATAL: BOOST_DIR needs to be set\n')
	sys.exit(1)

boost_include = os.sep.join([os.environ['BOOST_DIR'],'include'])
boost_lib = os.sep.join([os.environ['BOOST_DIR'],'lib'])

CXX = '/opt/local/bin/g++-mp-4.5'

env = Environment(CXX = CXX,
                  CCFLAGS = '--std=c++0x -DBOOST',
                  CPPPATH= ['.', boost_include])

env.Decider('MD5-timestamp')

env.Program('main', Glob('*.cpp'), 
            LIBS=['boost_regex'], 
            LIBPATH=boost_lib)
